services:
  angular-dev:
    build:
      context: .
      target: development
    ports:
      - "4200:4200"
    networks:
      - shared-net
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0", "--poll=2000"]

#  angular-prod:
#    build:
#      context: .
#      target: production
#    ports:
#      - "80:80"

networks:
  shared-net:
    driver: bridge
